language: python

python:
  - "3.7.6"

install:
  - pip install mkdocs
  - pip install mkdocs-material
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
  - sudo yum install -y golang
  - go get github.com/polym/upx

script:
  # 每次远程强制同步部署，该步骤会消出设置的自定义域名
  #- mkdocs gh-deploy --force --clean
  - mkdocs build --clean
  - upx login "${UPX_SERVICE_NAME}" "${UPX_OPERATOR}" "${UPX_PASSWORD}"
  - upx sync ./site/

branches:
  only:
    - master

