language: python

python:
  - "3.7.6"

install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pygments
  - pip install pymdown-extensions
  - pip install mkdocs-minify-plugin
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc


script:
  # 每次远程强制同步部署，该步骤会消出设置的自定义域名
  # - mkdocs gh-deploy --force --clean
  - mkdocs build --clean

branches:
  only:
    - master

#deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master
#   local_dir:
#     site/
