# Site info.
site_name: abookworm's Wiki
site_author: Aaron Loong
site_url: https://wiki.abookworm.site

# Repository
repo_name: abookworm-site/WikiPage
repo_url: https://github.com/abookworm-site/WikiPage

# Site Pre
# pip3 install mkdocs
# pip3 install mkdocs-material

# Site config
docs_dir: wiki


# Site theme
theme:
  name: 'material'
  language: 'zh'

  palette:
    primary: 'Light Blue'
    accent: 'Blue'
  favicon: '/favicon.ico'
  #feature:
    #tabs: false
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'

  #include_search_page: false
  #search_index_only: true
  #icon:
    #logo: material/library
    #repo: fontawesome/brands/git-alt


# mkdocs extension
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde


# Site Nav
nav:
- HomePage: 'index.md'

#- 230 Working Excellence:
#  - Content: '230 Working Excellence\index.md'

- 250 Working Coding: 
  - 操作系统底层: '250 Working Coding\操作系统底层\Java 程序员掌握的系统底层知识.md'
  - 数据库操作与配置:
    - Content: '250 Working Coding\数据库操作与配置\index.md'
  - Git & Github 代码管理: '250 Working Coding\Git & Github 代码管理\Git & Github.md'
  - Docker 与 K8s 容器技术: 
    - Docker 最佳实践: '250 Working Coding\Docker & K8s 容器技术\Docker 最佳实践.md'
    - Kubernetes(K8s) 最佳实践: '250 Working Coding\Docker & K8s 容器技术\Kubernetes(K8s) 最佳实践.md'
    - K8s 安装指引: '250 Working Coding\Docker & K8s 容器技术\K8s 安装指引.md'
    - K8s 端口转发工具 rinetd 安装配置指引: '250 Working Coding\Docker & K8s 容器技术\K8s 端口转发工具 rinetd 安装配置指引.md'
  - 环境安装与配置:
    - Content: '250 Working Coding\环境安装与配置\index.md'

- 250 Working Coding C:
  - Content: '250 Working Coding C\index.md'
- 250 Working Coding Java:
  - Content: '250 Working Coding Java\index.md'
- 250 Working Coding Python:
  - Content: '250 Working Coding Python\index.md'

- 260 Working Operating System:
  - Content: '260 Working Operating System\index.md' 
  - Linux System: '260 Working Operating System\Linux System\Linux Learning.md'