# Site info.
site_name: abookworm's Wiki
site_author: Aaron Loong
site_url: https://wiki.abookworm.site

# Repository
repo_name: abookworm-site/WikiPage
repo_url: https://github.com/abookworm-site/WikiPage

docs_dir: wiki

# Site Nav
nav:
- 首页: 'index.md'
- 编程: 'index.md'

