# Site info.
site_name: abookworm's Wiki
site_author: Aaron Loong
site_url: https://wiki.abookworm.site

# Repository
repo_name: abookworm-site/WikiPage
repo_url: https://github.com/abookworm-site/WikiPage

docs_dir: wiki

# Site theme
theme:
  name: 'material'


# Site Nav
nav:
- 首页: 'index.md'
- 250 Working Coding: '250 Working Coding/Git & Github.md'
  - Coding with C: '250 Working Coding/Coding with C/index.md'

