# Site info.
site_name: abookworm's Wiki
site_author: Aaron Loong
site_url: https://wiki.abookworm.site

# Repository
repo_name: abookworm-site/WikiPage
repo_url: https://github.com/abookworm-site/WikiPage

# Site Pre
# pip3 install mkdocs
# pip3 install mkdocs-material

# Site config
docs_dir: wiki


# Site theme
theme:
  name: 'material'
  language: 'zh'

  palette:
    primary: 'Light Green'
    accent: 'Pink'
  favicon: '/favicon.ico'
  feature:
    tabs: false
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  include_search_page: false
  search_index_only: true
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt



# mkdocs extension
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Site Nav
nav:
- Home: 'index.md'
- 250 Working Coding: 
  - Git & Github: '250 Working Coding\Git & Github\Git & Github.md'
  - Docker 与 K8s 最佳实践: 
    - K8s 安装指引: '250 Working Coding\Docker 与 K8s 最佳实践\K8s 安装指引.md'
    - K8s 端口转发工具 rinetd 安装配置指引: '250 Working Coding\Docker 与 K8s 最佳实践\K8s 端口转发工具 rinetd 安装配置指引.md'
  - Coding with C: 
    - 目录: '250 Working Coding\Coding with C\index.md'
